name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    env:
      PYTHON: ${{ matrix.python-version }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: install
      run: make install-dev
    - name: Lint
      run: make check
    - name: test
      run: make test
    - name: coverage
      run: make coverage

    - uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        env_vars: PYTHON

  deploy:
    name: Build and Deploy
    needs: test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: install
      run: make install-dev

    - name: build
      run: make build

    - name: upload to pypi
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_token }}
